apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s/minio-deployment.yaml
  - k8s/iceberg-pv.yaml
  - k8s/kafka.yaml
  - k8s/iceberg-rest.yaml
  - k8s/nifi.yaml
  - k8s/flink.yaml
configMapGenerator:
  - name: nifi-bootstrap
    namespace: data-platform
    behavior: replace
    files:
      - nifi_bootstrap.py=scripts/nifi_bootstrap.py
generatorOptions:
  disableNameSuffixHash: true
